import test from 'node:test';
import assert from 'node:assert/strict';
import { createPlayer, deletePlayer, loadPlayerState, migrateState, PLAYER_STORE, LEGACY_STORE, savePlayerState, selectedPlayer } from '../src/player-store.js';

const memoryStorage = initial => { const values = new Map(Object.entries(initial || {})); return { getItem:key=>values.get(key) ?? null, setItem:(key,value)=>values.set(key,value), values }; };
test('two players keep references and histories isolated and can switch', () => { const a=createPlayer({name:'A'},'a'),b=createPlayer({name:'B',dominantHand:'left'},'b');a.reference={id:'a-ref'};a.history.push({made:true});const state={version:3,players:[a,b],selectedPlayerId:'a'};assert.equal(selectedPlayer(state).reference.id,'a-ref');state.selectedPlayerId='b';assert.equal(selectedPlayer(state).reference,null);assert.equal(selectedPlayer(state).history.length,0); });
test('deleting a player removes its data and clears selection',()=>{const state={version:3,players:[createPlayer({name:'A'},'a'),createPlayer({name:'B'},'b')],selectedPlayerId:'a'};const next=deletePlayer(state,'a');assert.deepEqual(next.players.map(p=>p.id),['b']);assert.equal(next.selectedPlayerId,null)});
test('legacy reference and history migrate into the existing-data player',()=>{const legacy={reference:{frames:[1]},history:[{made:true}]};const state=migrateState(null,legacy);assert.equal(state.players[0].name,'既存データ');assert.deepEqual(state.players[0].reference,legacy.reference);assert.deepEqual(state.players[0].history,legacy.history)});
test('saved players remain after a simulated restart',()=>{const storage=memoryStorage();const state={version:3,players:[createPlayer({name:'Persist'},'p')],selectedPlayerId:'p'};savePlayerState(state,storage);const loaded=loadPlayerState(storage);assert.equal(loaded.players[0].name,'Persist');assert.equal(loaded.selectedPlayerId,'p');assert.ok(storage.values.has(PLAYER_STORE));assert.equal(storage.getItem(LEGACY_STORE),null)});
test('empty legacy state migrates safely without inventing a player',()=>{const state=migrateState(null,{reference:null,history:[]});assert.deepEqual(state.players,[]);assert.equal(state.selectedPlayerId,null)});
