import{CONNECTIONS,PHASES,analyzeFrame,inferPhases,phaseFrame,compareSequences,differenceScore,analysisFps,shouldSeek,coachingTip}from'./src/shot-utils.js';
const $=s=>document.querySelector(s);const STORE='shot-coach:sequence:v2';const ANALYSIS_FPS=analysisFps(navigator);const SEEK_TIMEOUT_MS=3000;const FRAME_TIMEOUT_MS=3000;let landmarker,current,videoUrl;let data=load();
const requiredAssets=new Map([
  ['./index.html',100],['./styles.css',100],['./app.js',100],['./src/shot-utils.js',100],
  ['./manifest.webmanifest',100],['./icons/icon.svg',100],
  ['./mediapipe/vision_bundle.mjs',10_000],
  ['./wasm/vision_wasm_internal.js',1_000],['./wasm/vision_wasm_internal.wasm',1_000_000],
  ['./wasm/vision_wasm_nosimd_internal.js',1_000],['./wasm/vision_wasm_nosimd_internal.wasm',1_000_000],
  ['./models/pose_landmarker_lite.task',1_000_000],
]);
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{reference:null,history:[]}}catch{return{reference:null,history:[]}}}function save(){localStorage.setItem(STORE,JSON.stringify(data))}const localUrl=path=>new URL(path,document.baseURI).href;
async function setupAI(){try{setStatus('ローカルAIモデルを準備しています…');const{FilesetResolver,PoseLandmarker}=await import(localUrl('./mediapipe/vision_bundle.mjs'));const vision=await FilesetResolver.forVisionTasks(localUrl('./wasm/'));landmarker=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:localUrl('./models/pose_landmarker_lite.task'),delegate:'GPU'},runningMode:'VIDEO',numPoses:1});$('#offlineBadge').textContent='AI準備完了';$('#offlineBadge').className='ready';setStatus('動画を選択してください')}catch(error){$('#offlineBadge').textContent='AI読込エラー';setStatus('ローカルAIファイルを読み込めませんでした。オフライン準備を確認してください。');console.error(error)}}
async function checkOffline(){
  const list=$('#offlineFiles');list.innerHTML='確認中…';
  const results=await Promise.all([...requiredAssets].map(async([path,minimumBytes])=>{try{
    const response=await fetch(localUrl(path),{cache:'reload'});if(!response.ok)throw Error(`HTTP ${response.status}`);
    const bytes=(await response.arrayBuffer()).byteLength;if(bytes<minimumBytes)throw Error(`${bytes} bytes`);
    return{path,ok:true,bytes};
  }catch(error){return{path,ok:false,error:error.message}}}));
  const missing=results.filter(item=>!item.ok);
  $('#offlineState').textContent=missing.length?`不足または不正なファイル: ${missing.length}件`:'✓ オフライン使用準備完了';
  $('#offlineState').className=missing.length?'error':'ready';
  list.innerHTML=missing.length?missing.map(item=>`<li>${item.path} — ${item.error}</li>`).join(''):results.map(item=>`<li>${item.path} — ${item.bytes.toLocaleString()} bytes</li>`).join('');
  return!missing.length;
}
$('#offlineCheck').onclick=checkOffline;$('#offlineToggle').onclick=()=>{const details=$('#offlineDetails'),willOpen=details.hidden;details.hidden=!willOpen;$('#offlineToggle').textContent=willOpen?'詳細を隠す':'詳細を見る';$('#offlineToggle').setAttribute('aria-expanded',String(willOpen))};
$('#cameraButton').onclick=()=>$('#cameraInput').click();const loadVideo=e=>{const file=e.target.files[0];if(!file)return;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(file);const v=$('#video');v.src=videoUrl;$('#stage').hidden=false;$('#analysisControls').hidden=false;v.onloadedmetadata=resize;setStatus('解析区間を確認して「動画を連続解析」を押してください')};$('#videoInput').onchange=loadVideo;$('#cameraInput').onchange=loadVideo;addEventListener('resize',resize);function resize(){const v=$('#video'),c=$('#overlay');c.width=v.videoWidth||640;c.height=v.videoHeight||360}
function seek(video,time,timeoutMs=SEEK_TIMEOUT_MS){const target=Math.min(Math.max(0,time),Math.max(0,video.duration-.001));if(!shouldSeek(video.currentTime,target))return Promise.resolve();return new Promise((resolve,reject)=>{let timer;const cleanup=()=>{clearTimeout(timer);video.removeEventListener('seeked',onSeeked);video.removeEventListener('error',onError)};const finish=()=>{cleanup();resolve()};const fail=()=>{cleanup();reject(Error('seek-error'))};const onSeeked=()=>finish();const onError=()=>fail();video.addEventListener('seeked',onSeeked,{once:true});video.addEventListener('error',onError,{once:true});timer=setTimeout(()=>{cleanup();reject(Error('seek-timeout'))},timeoutMs);try{video.currentTime=target}catch{fail()}})}
const videoIsReady=video=>video.readyState>=HTMLMediaElement.HAVE_CURRENT_DATA&&Number.isFinite(video.duration)&&video.duration>0&&video.videoWidth>0&&video.videoHeight>0;
function waitForVideoReady(video,timeoutMs=10000){if(videoIsReady(video))return Promise.resolve();setStatus('動画を準備しています…');return new Promise((resolve,reject)=>{let timer;const cleanup=()=>{clearTimeout(timer);video.removeEventListener('loadedmetadata',check);video.removeEventListener('loadeddata',check);video.removeEventListener('error',fail)};const check=()=>{if(videoIsReady(video)){cleanup();resolve()}};const fail=()=>{cleanup();reject(Error('動画を読み込めませんでした'))};video.addEventListener('loadedmetadata',check);video.addEventListener('loadeddata',check);video.addEventListener('error',fail,{once:true});timer=setTimeout(()=>{cleanup();reject(Error('動画の準備が完了しませんでした。もう一度選択してください'))},timeoutMs);video.load();check()})}
$('#analyzeButton').onclick=async()=>{if(!landmarker)return toast('AIモデルが利用できません');const button=$('#analyzeButton'),progress=$('#progress'),v=$('#video');button.disabled=true;progress.value=0;try{if(!await checkOffline()){setStatus('不足ファイルがあるため解析を開始できません');return}await waitForVideoReady(v);resize();const frames=[],step=1/ANALYSIS_FPS,total=Math.max(1,Math.ceil(v.duration*ANALYSIS_FPS));$('#analysisFps').textContent=`解析 ${ANALYSIS_FPS} fps`;setStatus(`解析中 0 / ${total}フレーム（0%・${ANALYSIS_FPS}fps）`);for(let index=0;index<total;index++){const time=Math.min(index*step,Math.max(0,v.duration-.001));try{await seek(v,time)}catch{throw Error(`この動画の${time.toFixed(1)}秒付近を読み込めませんでした`)}const started=performance.now();const result=landmarker.detectForVideo(v,time*1000);if(performance.now()-started>FRAME_TIMEOUT_MS)throw Error(`この動画の${time.toFixed(1)}秒付近の解析に時間がかかりすぎました`);if(result.landmarks?.[0])frames.push({...analyzeFrame(result.landmarks[0],time*1000),landmarks:result.landmarks[0]});const completed=index+1,percent=Math.round(completed/total*100);progress.value=completed/total;setStatus(`解析中 ${completed} / ${total}フレーム（${percent}%・${ANALYSIS_FPS}fps）`);await new Promise(requestAnimationFrame)}if(!frames.length)throw Error('身体を検出できませんでした');const releaseMs=Number($('#releaseSlider').value)/100*v.duration*1000;current={frames,phases:inferPhases(frames,releaseMs),durationMs:Math.round(v.duration*1000),fps:ANALYSIS_FPS,releaseLandmarks:null};const release=current.phases.find(p=>p.name==='リリース付近');current.releaseLandmarks=phaseFrame(frames,release).landmarks||null;renderAnalysis();setStatus(`${frames.length}フレームを${ANALYSIS_FPS}fpsで解析しました`)}catch(error){setStatus(error.message||'解析できませんでした')}finally{button.disabled=false}};
$('#releaseSlider').oninput=()=>{$('#releaseValue').textContent=`${$('#releaseSlider').value}%`;if(current){const v=$('#video');current.phases=inferPhases(current.frames,Number($('#releaseSlider').value)/100*v.duration*1000);current.releaseLandmarks=phaseFrame(current.frames,current.phases[3]).landmarks||null;renderAnalysis()}};
function renderAnalysis(){const phases=$('#phases');phases.innerHTML=current.phases.map(p=>`<button data-time="${p.timeMs}" class="${p.manual?'manual':''}"><b>${p.name}</b><small>${(p.timeMs/1000).toFixed(2)}秒</small></button>`).join('');phases.querySelectorAll('button').forEach(b=>b.onclick=async()=>{await seek($('#video'),Number(b.dataset.time)/1000);draw(current.releaseLandmarks)});const release=phaseFrame(current.frames,current.phases[3]);$('#metrics').innerHTML=metricCards(release);const comparison=data.reference?compareSequences(current,data.reference):[];$('#comparison').hidden=!comparison.length;renderComparison(comparison);$('#todayTip').textContent=coachingTip(comparison);$('#result').hidden=false;draw(current.releaseLandmarks);$('#result').scrollIntoView({behavior:'smooth'})}
function renderComparison(comparison){if(!comparison.length){$('#diffs').innerHTML='';$('#largeDiffs').innerHTML='';return}const ranked=comparison.map(p=>({...p,score:differenceScore(p.metrics)})).sort((a,b)=>b.score-a.score);const biggest=ranked.filter(p=>p.score>=1).slice(0,3);const overall=ranked[0].score;const status=$('#comparisonStatus');status.textContent=overall<.6?'よく一致':overall<1?'あと少し':'差をチェック';status.className=`comparison-status ${overall<.6?'good':overall>=1?'alert':''}`;$('#largeDiffs').innerHTML=biggest.length?`<strong>差が大きいポイント</strong><div class="difference-chips">${biggest.map(p=>`<span>${p.name}</span>`).join('')}</div>`:'<strong>大きな差はありません</strong>';$('#diffs').innerHTML=comparison.map(p=>{const score=differenceScore(p.metrics),level=score<.6?'good':score<1?'caution':'alert';return`<article class="is-${level}"><b>${p.name}</b><span class="diff-value">右 ${signed(p.metrics.rightKnee)}° / 左 ${signed(p.metrics.leftKnee)}°</span><span class="diff-value">${signed(p.metrics.shootingElbow)}°</span><span class="diff-value">${signed(p.metrics.stanceWidth)} / ${signed(p.metrics.footOffset)}</span></article>`}).join('')}
function metricCards(m){const items=[['右膝',m.rightKnee,'°'],['左膝',m.leftKnee,'°'],['シュート側肘',m.shootingElbow,'°'],['上体',m.trunk,'°'],['足幅',m.stanceWidth,'肩幅比'],['足の前後',m.footOffset,'肩幅比'],['腰の高さ',m.hipHeight,'肩幅比'],['肩の高さ',m.shoulderHeight,'肩幅比'],['信頼度',m.confidence,'%']];return items.map(([n,v,u])=>`<div><span>${n}</span><strong>${v}<small>${u}</small></strong></div>`).join('')}
function signed(n){return`${n>0?'+':''}${n}`}function draw(points){const c=$('#overlay'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const skeleton=(p,color)=>{if(!p)return;x.strokeStyle=color;x.lineWidth=Math.max(3,c.width/180);for(const[a,b]of CONNECTIONS){if(!p[a]||!p[b])continue;x.beginPath();x.moveTo(p[a].x*c.width,p[a].y*c.height);x.lineTo(p[b].x*c.width,p[b].y*c.height);x.stroke()}};skeleton(data.reference?.releaseLandmarks,'#ff7650');skeleton(points,'#dcff45')}
$('#makeButton').onclick=()=>record(true);$('#missButton').onclick=()=>record(false);function record(made){if(!current)return;const cleanFrames=current.frames.map(({landmarks,...frame})=>frame);const saved={...current,frames:cleanFrames,releaseLandmarks:current.releaseLandmarks?.map(({x,y,z,visibility})=>({x,y,z,visibility})),createdAt:new Date().toISOString(),made};data.history.unshift({...saved,releaseLandmarks:null});if(made)data.reference=saved;save();renderHistory();toast(made?'成功シーケンスを基準フォームに保存しました':'失敗を記録しました')}
function renderHistory(){$('#history').innerHTML=data.history.length?data.history.slice(0,30).map(x=>`<article class="history"><b class="${x.made?'made':'miss'}">${x.made?'成功':'失敗'}</b><span>${new Date(x.createdAt).toLocaleString('ja-JP')}</span><small>${x.frames.length}フレーム · ${x.fps}fps · ${(x.durationMs/1000).toFixed(1)}秒</small></article>`).join(''):'<p class="empty">まだ記録がありません</p>'}
$('#clearButton').onclick=()=>{if(confirm('基準フォームを含むすべての記録を削除しますか？')){data={reference:null,history:[]};save();renderHistory()}};function setStatus(s){$('#status').textContent=s}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderHistory();checkOffline().then(ok=>ok&&setupAI());
