import{CONNECTIONS,PHASES,analyzeFrame,inferPhases,phaseFrame,compareSequences,differenceScore,coachingTip}from'./src/shot-utils.js';
import{createPlayer,loadPlayerState,savePlayerState,selectedPlayer,deletePlayer}from'./src/player-store.js';
const $=s=>document.querySelector(s);const ANALYSIS_FPS=12;let landmarker,current,videoUrl;let data=loadPlayerState();savePlayerState(data);
const player=()=>selectedPlayer(data);const save=()=>savePlayerState(data);
const requiredAssets=new Map([
  ['./index.html',100],['./styles.css',100],['./app.js',100],['./src/shot-utils.js',100],['./src/player-store.js',100],
  ['./manifest.webmanifest',100],['./icons/icon.svg',100],
  ['./mediapipe/vision_bundle.mjs',10_000],
  ['./wasm/vision_wasm_internal.js',1_000],['./wasm/vision_wasm_internal.wasm',1_000_000],
  ['./wasm/vision_wasm_nosimd_internal.js',1_000],['./wasm/vision_wasm_nosimd_internal.wasm',1_000_000],
  ['./models/pose_landmarker_lite.task',1_000_000],
]);
const localUrl=path=>new URL(path,document.baseURI).href;
async function setupAI(){try{setStatus('ローカルAIモデルを準備しています…');const{FilesetResolver,PoseLandmarker}=await import(localUrl('./mediapipe/vision_bundle.mjs'));const vision=await FilesetResolver.forVisionTasks(localUrl('./wasm/'));landmarker=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:localUrl('./models/pose_landmarker_lite.task'),delegate:'GPU'},runningMode:'VIDEO',numPoses:1});$('#offlineBadge').textContent='AI準備完了';$('#offlineBadge').className='ready';setStatus('動画を選択してください')}catch(error){$('#offlineBadge').textContent='AI読込エラー';setStatus('ローカルAIファイルを読み込めませんでした。オフライン準備を確認してください。');console.error(error)}}
async function checkOffline(){
  const list=$('#offlineFiles');list.innerHTML='確認中…';
  const results=await Promise.all([...requiredAssets].map(async([path,minimumBytes])=>{try{
    const response=await fetch(localUrl(path),{cache:'reload'});if(!response.ok)throw Error(`HTTP ${response.status}`);
    const bytes=(await response.arrayBuffer()).byteLength;if(bytes<minimumBytes)throw Error(`${bytes} bytes`);
    return{path,ok:true,bytes};
  }catch(error){return{path,ok:false,error:error.message}}}));
  const missing=results.filter(item=>!item.ok);
  $('#offlineState').textContent=missing.length?`不足または不正なファイル: ${missing.length}件`:'✓ オフライン使用準備完了';
  $('#offlineState').className=missing.length?'error':'ready';
  list.innerHTML=missing.length?missing.map(item=>`<li>${item.path} — ${item.error}</li>`).join(''):results.map(item=>`<li>${item.path} — ${item.bytes.toLocaleString()} bytes</li>`).join('');
  return!missing.length;
}
$('#offlineCheck').onclick=checkOffline;$('#offlineToggle').onclick=()=>{const details=$('#offlineDetails'),willOpen=details.hidden;details.hidden=!willOpen;$('#offlineToggle').textContent=willOpen?'詳細を隠す':'詳細を見る';$('#offlineToggle').setAttribute('aria-expanded',String(willOpen))};
$('#cameraButton').onclick=()=>$('#cameraInput').click();const loadVideo=e=>{if(!player()){e.target.value='';showTab('players');return toast('解析する選手を選択してください')}const file=e.target.files[0];if(!file)return;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(file);const v=$('#video');v.src=videoUrl;$('#stage').hidden=false;$('#analysisControls').hidden=false;v.onloadedmetadata=resize;setStatus('解析区間を確認して「動画を連続解析」を押してください')};$('#videoInput').onchange=loadVideo;$('#cameraInput').onchange=loadVideo;addEventListener('resize',resize);function resize(){const v=$('#video'),c=$('#overlay');c.width=v.videoWidth||640;c.height=v.videoHeight||360}
const seek=(video,time)=>new Promise(resolve=>{const done=()=>{video.removeEventListener('seeked',done);resolve()};video.addEventListener('seeked',done);video.currentTime=Math.min(time,Math.max(0,video.duration-.001))});
$('#analyzeButton').onclick=async()=>{if(!player())return toast('解析する選手を選択してください');if(!landmarker)return toast('AIモデルが利用できません');if(!await checkOffline())return setStatus('不足ファイルがあるため解析を開始できません');const v=$('#video');if(!v.duration)return;$('#analyzeButton').disabled=true;const frames=[],step=1/ANALYSIS_FPS;setStatus(`動画を約${ANALYSIS_FPS}fpsで解析中…`);try{for(let time=0;time<v.duration;time+=step){await seek(v,time);const result=landmarker.detectForVideo(v,time*1000);if(result.landmarks?.[0])frames.push({...analyzeFrame(result.landmarks[0],time*1000),landmarks:result.landmarks[0]});$('#progress').value=Math.min(1,time/v.duration);await new Promise(requestAnimationFrame)}if(!frames.length)throw Error('身体を検出できませんでした');const releaseMs=Number($('#releaseSlider').value)/100*v.duration*1000;current={frames,phases:inferPhases(frames,releaseMs),durationMs:Math.round(v.duration*1000),fps:ANALYSIS_FPS,releaseLandmarks:null};const release=current.phases.find(p=>p.name==='リリース付近');current.releaseLandmarks=phaseFrame(frames,release).landmarks||null;renderAnalysis();setStatus(`${frames.length}フレームを解析しました`)}catch(error){setStatus(error.message||'解析できませんでした')}finally{$('#analyzeButton').disabled=false;$('#progress').value=0}};
$('#releaseSlider').oninput=()=>{$('#releaseValue').textContent=`${$('#releaseSlider').value}%`;if(current){const v=$('#video');current.phases=inferPhases(current.frames,Number($('#releaseSlider').value)/100*v.duration*1000);current.releaseLandmarks=phaseFrame(current.frames,current.phases[3]).landmarks||null;renderAnalysis()}};
function renderAnalysis(){const phases=$('#phases');phases.innerHTML=current.phases.map(p=>`<button data-time="${p.timeMs}" class="${p.manual?'manual':''}"><b>${p.name}</b><small>${(p.timeMs/1000).toFixed(2)}秒</small></button>`).join('');phases.querySelectorAll('button').forEach(b=>b.onclick=async()=>{await seek($('#video'),Number(b.dataset.time)/1000);draw(current.releaseLandmarks)});const release=phaseFrame(current.frames,current.phases[3]);$('#metrics').innerHTML=metricCards(release);const comparison=player()?.reference?compareSequences(current,player().reference):[];$('#comparison').hidden=!comparison.length;renderComparison(comparison);$('#todayTip').textContent=coachingTip(comparison);$('#result').hidden=false;draw(current.releaseLandmarks);$('#result').scrollIntoView({behavior:'smooth'})}
function renderComparison(comparison){if(!comparison.length){$('#diffs').innerHTML='';$('#largeDiffs').innerHTML='';return}const ranked=comparison.map(p=>({...p,score:differenceScore(p.metrics)})).sort((a,b)=>b.score-a.score);const biggest=ranked.filter(p=>p.score>=1).slice(0,3);const overall=ranked[0].score;const status=$('#comparisonStatus');status.textContent=overall<.6?'よく一致':overall<1?'あと少し':'差をチェック';status.className=`comparison-status ${overall<.6?'good':overall>=1?'alert':''}`;$('#largeDiffs').innerHTML=biggest.length?`<strong>差が大きいポイント</strong><div class="difference-chips">${biggest.map(p=>`<span>${p.name}</span>`).join('')}</div>`:'<strong>大きな差はありません</strong>';$('#diffs').innerHTML=comparison.map(p=>{const score=differenceScore(p.metrics),level=score<.6?'good':score<1?'caution':'alert';return`<article class="is-${level}"><b>${p.name}</b><span class="diff-value">右 ${signed(p.metrics.rightKnee)}° / 左 ${signed(p.metrics.leftKnee)}°</span><span class="diff-value">${signed(p.metrics.shootingElbow)}°</span><span class="diff-value">${signed(p.metrics.stanceWidth)} / ${signed(p.metrics.footOffset)}</span></article>`}).join('')}
function metricCards(m){const items=[['右膝',m.rightKnee,'°'],['左膝',m.leftKnee,'°'],['シュート側肘',m.shootingElbow,'°'],['上体',m.trunk,'°'],['足幅',m.stanceWidth,'肩幅比'],['足の前後',m.footOffset,'肩幅比'],['腰の高さ',m.hipHeight,'肩幅比'],['肩の高さ',m.shoulderHeight,'肩幅比'],['信頼度',m.confidence,'%']];return items.map(([n,v,u])=>`<div><span>${n}</span><strong>${v}<small>${u}</small></strong></div>`).join('')}
function signed(n){return`${n>0?'+':''}${n}`}function draw(points){const c=$('#overlay'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const skeleton=(p,color)=>{if(!p)return;x.strokeStyle=color;x.lineWidth=Math.max(3,c.width/180);for(const[a,b]of CONNECTIONS){if(!p[a]||!p[b])continue;x.beginPath();x.moveTo(p[a].x*c.width,p[a].y*c.height);x.lineTo(p[b].x*c.width,p[b].y*c.height);x.stroke()}};skeleton(player()?.reference?.releaseLandmarks,'#ff7650');skeleton(points,'#dcff45')}
$('#makeButton').onclick=()=>record(true);$('#missButton').onclick=()=>record(false);function record(made){const owner=player();if(!current||!owner)return toast('解析する選手を選択してください');const cleanFrames=current.frames.map(({landmarks,...frame})=>frame);const saved={...current,frames:cleanFrames,releaseLandmarks:current.releaseLandmarks?.map(({x,y,z,visibility})=>({x,y,z,visibility})),createdAt:new Date().toISOString(),made};owner.history.unshift({...saved,releaseLandmarks:null});if(made)owner.reference=saved;save();renderAll();toast(made?'成功シーケンスをこの選手の基準フォームに保存しました':'失敗を記録しました')}
function historyMarkup(owner,limit=30){return owner?.history.length?owner.history.slice(0,limit).map(x=>`<article class="history"><b class="${x.made?'made':'miss'}">${x.made?'成功':'失敗'}</b><span>${new Date(x.createdAt).toLocaleString('ja-JP')}</span><small>${x.frames.length}フレーム · ${x.fps}fps · ${(x.durationMs/1000).toFixed(1)}秒</small></article>`).join(''):'<p class="empty">まだ記録がありません</p>'}
function renderHistory(){const owner=player();$('#historyOwner').textContent=owner?`${displayName(owner)}さんの履歴`:'選手を選択してください';$('#history').innerHTML=historyMarkup(owner)}
$('#clearButton').onclick=()=>{const owner=player();if(owner&&confirm(`${displayName(owner)}さんの基準フォームを含むすべての記録を削除しますか？`)){owner.reference=null;owner.history=[];save();renderAll()}};function setStatus(s){$('#status').textContent=s}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function displayName(p){return p.nickname||p.name}
function showTab(name){document.querySelectorAll('.tab-panel').forEach(panel=>panel.hidden=panel.id!==`${name}Panel`);document.querySelectorAll('.tabs button').forEach(button=>button.classList.toggle('active',button.dataset.tab===name));if(name==='players')showPlayerList()}
document.querySelectorAll('.tabs button').forEach(button=>button.onclick=()=>showTab(button.dataset.tab));$('#changePlayer').onclick=()=>showTab('players');
function selectPlayer(id,openDashboard=false){data.selectedPlayerId=id;current=null;save();renderAll();if(openDashboard){showTab('players');showDashboard()}else showTab('analysis')}
function renderPlayers(){const cards=$('#playerCards');cards.innerHTML=data.players.length?data.players.map((p,i)=>{const made=p.history.filter(x=>x.made).length;const latest=p.history[0]?.createdAt;return `<article class="player-card" data-id="${p.id}" tabindex="0"><small>PLAYER ${String(i+1).padStart(2,'0')}</small><h2>${escapeHtml(displayName(p))}</h2><p>${p.dominantHand==='left'?'左':'右'}利き</p><strong>成功フォーム ${made}本</strong><span>最終解析 ${latest?new Date(latest).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'}):'未解析'}</span><div class="card-actions"><button class="text edit-player">編集</button><button class="text delete-player">削除</button></div></article>`}).join(''):'<p class="empty">選手がまだ登録されていません。「＋ 選手を追加」から始めましょう。</p>';cards.querySelectorAll('.player-card').forEach(card=>{card.onclick=e=>{if(e.target.closest('button'))return;selectPlayer(card.dataset.id,true)};card.onkeydown=e=>{if(e.key==='Enter')selectPlayer(card.dataset.id,true)}});cards.querySelectorAll('.edit-player').forEach(b=>b.onclick=e=>openPlayerForm(data.players.find(p=>p.id===e.target.closest('.player-card').dataset.id)));cards.querySelectorAll('.delete-player').forEach(b=>b.onclick=e=>openDelete(data.players.find(p=>p.id===e.target.closest('.player-card').dataset.id)))}
function renderAll(){const owner=player();$('#activePlayer').textContent=owner?`解析中：${displayName(owner)}`:'解析する選手を選択してください';renderPlayers();renderHistory();if(!$('#playerDashboard').hidden&&owner)renderDashboard(owner)}
function showPlayerList(){$('#playerCards').hidden=false;$('#addPlayer').hidden=false;$('#playerDashboard').hidden=true;renderPlayers()}
function showDashboard(){const owner=player();if(!owner)return;$('#playerCards').hidden=true;$('#addPlayer').hidden=true;$('#playerDashboard').hidden=false;renderDashboard(owner)}
function renderDashboard(owner){const successful=owner.history.filter(x=>x.made).length;let recent='比較データなし',tip=owner.reference?'次の解析で基準フォームとの差を確認しましょう':'成功フォームを登録しましょう';if(owner.reference&&owner.history[0]){const diffs=compareSequences(owner.history[0],owner.reference);const score=diffs.length?Math.max(...diffs.map(x=>differenceScore(x.metrics))):0;recent=score<.6?'小さい':score<1?'ややあり':'大きい';tip=coachingTip(diffs)}$('#dashboardTitle').textContent=`${displayName(owner)}さんのシュート解析`;$('#dashboardStats').innerHTML=`<div><span>解析回数</span><strong>${owner.history.length}</strong></div><div><span>成功記録数</span><strong>${successful}</strong></div><div><span>基準フォーム</span><strong>${owner.reference?'登録済み':'未登録'}</strong></div><div><span>最近のフォーム差</span><strong>${recent}</strong></div>`;$('#dashboardTip').textContent=tip;$('#dashboardComparison').textContent=owner.reference?'基準フォームとの6フェーズ比較が利用できます。':'成功を記録するとフェーズ別比較が表示されます。';$('#dashboardHistory').innerHTML=historyMarkup(owner,10)}
function openPlayerForm(p=null){$('#playerForm').reset();$('#editingId').value=p?.id||'';$('#formTitle').textContent=p?'選手を編集':'選手を追加';$('#playerName').value=p?.name||'';$('#playerNickname').value=p?.nickname||'';$('#playerMemo').value=p?.memo||'';document.querySelector(`input[name="dominantHand"][value="${p?.dominantHand||'right'}"]`).checked=true;$('#playerDialog').showModal()}
$('#addPlayer').onclick=()=>openPlayerForm();document.querySelector('.dialog-close').onclick=()=>$('#playerDialog').close();$('#playerForm').onsubmit=e=>{e.preventDefault();const values={name:$('#playerName').value,nickname:$('#playerNickname').value,dominantHand:new FormData(e.target).get('dominantHand'),memo:$('#playerMemo').value},id=$('#editingId').value;if(id)Object.assign(data.players.find(p=>p.id===id),values);else{const added=createPlayer(values);data.players.push(added);data.selectedPlayerId=added.id}save();$('#playerDialog').close();renderAll();toast(id?'選手情報を更新しました':'選手を追加しました')};
let pendingDelete=null;function openDelete(p){pendingDelete=p;$('#deleteTitle').textContent=`${displayName(p)}さんのデータを削除しますか？`;$('#deleteDialog').showModal()}$('#cancelDelete').onclick=()=>$('#deleteDialog').close();$('#confirmDelete').onclick=()=>{if(pendingDelete){data=deletePlayer(data,pendingDelete.id);save();pendingDelete=null;$('#deleteDialog').close();showPlayerList();renderAll();toast('選手データを削除しました')}};
$('#backToPlayers').onclick=showPlayerList;$('#analyzeThisPlayer').onclick=()=>showTab('analysis');
function escapeHtml(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderAll();checkOffline().then(ok=>ok&&setupAI());
